# Generated by Django 5.0.4 on 2024-06-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zencoder_job_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
