# Generated by Django 5.0.4 on 2024-06-10 10:38

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_thumbnail_alter_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv']), posts.models.validate_mime_type]),
        ),
    ]
